CREATE TABLE COMPETENZE_DELEGA
(
  ID_COMPETENZA_DELEGA  NUMBER                  NOT NULL,
  DESCRIZIONE           VARCHAR2(4000 BYTE)     NOT NULL,
  CODICE                VARCHAR2(255 BYTE)      NOT NULL,
  ID_APPLICATIVO        NUMBER                  NOT NULL,
  FINE_VALIDITA         DATE,
  UTENTE_AGGIORNAMENTO  VARCHAR2(8 BYTE),
  DATA_AGGIORNAMENTO    DATE
)
TABLESPACE SO4
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            MAXSIZE          UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );


