CREATE TABLE KEY_CONSTRAINT
(
  OGGETTO         VARCHAR2(30 BYTE)             NOT NULL,
  TIPO            VARCHAR2(2 BYTE)              NOT NULL,
  SEQUENZA        NUMBER(3)                     NOT NULL,
  NOME            VARCHAR2(30 BYTE)             NOT NULL,
  NOTE            VARCHAR2(240 BYTE),
  PROCEDURA       LONG,
  LABEL_SUCCESS   VARCHAR2(30 BYTE),
  FLAG_ABORT      VARCHAR2(1 BYTE),
  LABEL_FAILURE   VARCHAR2(30 BYTE),
  RIF_OGGETTO     VARCHAR2(30 BYTE),
  RIF_DESCRIPTOR  VARCHAR2(240 BYTE),
  CASCADE_UPDATE  VARCHAR2(1 BYTE),
  CASCADE_DELETE  VARCHAR2(1 BYTE)
)
TABLESPACE SO4
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            MAXSIZE          UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );


