CREATE TABLE KEY_ERROR_LOG
(
  ERROR_ID        NUMBER                        NOT NULL,
  ERROR_SESSION   NUMBER,
  ERROR_DATE      DATE,
  ERROR_TEXT      VARCHAR2(2000 BYTE),
  ERROR_USER      VARCHAR2(8 BYTE),
  ERROR_USERTEXT  VARCHAR2(2000 BYTE),
  ERROR_TYPE      VARCHAR2(1 BYTE)
)
TABLESPACE SO4
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            MAXSIZE          UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

COMMENT ON TABLE KEY_ERROR_LOG IS 'KEEL - Tabella degli Errori di applicazione';



