CREATE TABLE P00_POSIZIONI
(
  CODICE                VARCHAR2(4 BYTE),
  CONTRATTO_FORMAZIONE  VARCHAR2(2 BYTE),
  TEMPO_DETERMINATO     VARCHAR2(2 BYTE),
  PART_TIME             VARCHAR2(2 BYTE),
  DI_RUOLO              VARCHAR2(1 BYTE),
  RUOLO                 VARCHAR2(2 BYTE),
  COLLABORATORE         VARCHAR2(2 BYTE)
)
TABLESPACE SO4
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            MAXSIZE          UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );


