CREATE TABLE P00_FIGURE_GIURIDICHE
(
  NUMERO     NUMBER(8),
  CODICE     VARCHAR2(4 BYTE),
  PROFILO    VARCHAR2(8 BYTE),
  POSIZIONE  VARCHAR2(8 BYTE),
  DAL        DATE,
  AL         DATE
)
TABLESPACE SO4
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            MAXSIZE          UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );


