CREATE TABLE RELAZIONI_UNITA_ORGANIZZATIVE
(
  ID_RELAZIONI_STRUTTURA  NUMBER(10)            NOT NULL,
  AMMINISTRAZIONE         VARCHAR2(50 BYTE),
  DESCR_AMMINISTRAZIONE   VARCHAR2(240 BYTE),
  COD_AOO                 VARCHAR2(50 BYTE),
  DESCR_AOO               VARCHAR2(240 BYTE),
  OTTICA                  VARCHAR2(18 BYTE),
  DESCR_OTTICA            VARCHAR2(120 BYTE),
  REVISIONE               NUMBER(8)             NOT NULL,
  PROGR_PADRE             NUMBER(8),
  COD_PADRE               VARCHAR2(50 BYTE),
  DESCR_PADRE             VARCHAR2(240 BYTE),
  SUDD_PADRE              VARCHAR2(8 BYTE),
  SEQUENZA_PADRE          NUMBER(6),
  DAL_PADRE               DATE,
  AL_PADRE                DATE,
  LIV_PADRE               NUMBER(2),
  PROGR_FIGLIO            NUMBER(8),
  COD_FIGLIO              VARCHAR2(50 BYTE),
  DESCR_FIGLIO            VARCHAR2(240 BYTE),
  SUDD_FIGLIO             VARCHAR2(8 BYTE),
  SEQUENZA_FIGLIO         NUMBER(6),
  DAL_FIGLIO              DATE,
  AL_FIGLIO               DATE,
  LIV_FIGLIO              NUMBER(2),
  ORDINAMENTO             VARCHAR2(4000 BYTE),
  PROGR_PADRE_EFFETTIVO   NUMBER(8)
)
TABLESPACE SO4
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            MAXSIZE          UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

COMMENT ON TABLE RELAZIONI_UNITA_ORGANIZZATIVE IS 'Relazioni reciproche tra unità organizzative';

COMMENT ON COLUMN RELAZIONI_UNITA_ORGANIZZATIVE.ID_RELAZIONI_STRUTTURA IS 'Identificativo della riga (sequence)';

COMMENT ON COLUMN RELAZIONI_UNITA_ORGANIZZATIVE.AMMINISTRAZIONE IS 'Amministrazione di riferimento';

COMMENT ON COLUMN RELAZIONI_UNITA_ORGANIZZATIVE.DESCR_AMMINISTRAZIONE IS 'Descrizione dell''amministrazione di riferimento';

COMMENT ON COLUMN RELAZIONI_UNITA_ORGANIZZATIVE.COD_AOO IS 'Codice dell''AOO di riferimento';

COMMENT ON COLUMN RELAZIONI_UNITA_ORGANIZZATIVE.DESCR_AOO IS 'Descrizione dell''AOO di riferimento';

COMMENT ON COLUMN RELAZIONI_UNITA_ORGANIZZATIVE.OTTICA IS 'Ottica di riferimento';

COMMENT ON COLUMN RELAZIONI_UNITA_ORGANIZZATIVE.DESCR_OTTICA IS 'Descrizone dell''ottica';

COMMENT ON COLUMN RELAZIONI_UNITA_ORGANIZZATIVE.REVISIONE IS 'Revisione di struttura di riferimento';

COMMENT ON COLUMN RELAZIONI_UNITA_ORGANIZZATIVE.PROGR_PADRE IS 'Progressivo dell''unita'' padre';

COMMENT ON COLUMN RELAZIONI_UNITA_ORGANIZZATIVE.COD_PADRE IS 'Codice dell''unita'' padre';

COMMENT ON COLUMN RELAZIONI_UNITA_ORGANIZZATIVE.DESCR_PADRE IS 'Descrizione dell''unita'' padre';

COMMENT ON COLUMN RELAZIONI_UNITA_ORGANIZZATIVE.SUDD_PADRE IS 'Codice suddivisione dell''unita'' padre';

COMMENT ON COLUMN RELAZIONI_UNITA_ORGANIZZATIVE.SEQUENZA_PADRE IS 'Sequenza unita'' padre';

COMMENT ON COLUMN RELAZIONI_UNITA_ORGANIZZATIVE.DAL_PADRE IS 'Decorrenza della relazione per l''unita'' padre';

COMMENT ON COLUMN RELAZIONI_UNITA_ORGANIZZATIVE.AL_PADRE IS 'Termine della relazione per l''unita'' padre';

COMMENT ON COLUMN RELAZIONI_UNITA_ORGANIZZATIVE.LIV_PADRE IS 'Livello di nesting dell''unita'' padre';

COMMENT ON COLUMN RELAZIONI_UNITA_ORGANIZZATIVE.PROGR_FIGLIO IS 'Progressivo dell''unita'' figlio';

COMMENT ON COLUMN RELAZIONI_UNITA_ORGANIZZATIVE.COD_FIGLIO IS 'Codice dell''unita'' figlio';

COMMENT ON COLUMN RELAZIONI_UNITA_ORGANIZZATIVE.DESCR_FIGLIO IS 'Descrizione dell''unita'' figlio';

COMMENT ON COLUMN RELAZIONI_UNITA_ORGANIZZATIVE.SUDD_FIGLIO IS 'Codice suddivisione dell''unita'' figlio';

COMMENT ON COLUMN RELAZIONI_UNITA_ORGANIZZATIVE.SEQUENZA_FIGLIO IS 'Sequenza unita'' figlio';

COMMENT ON COLUMN RELAZIONI_UNITA_ORGANIZZATIVE.DAL_FIGLIO IS 'Decorrenza della relazione per l''unita'' figlio';

COMMENT ON COLUMN RELAZIONI_UNITA_ORGANIZZATIVE.AL_FIGLIO IS 'Termine della relazione per l''unita'' figlio';

COMMENT ON COLUMN RELAZIONI_UNITA_ORGANIZZATIVE.LIV_FIGLIO IS 'Livello di nesting dell''unita'' figlio';

COMMENT ON COLUMN RELAZIONI_UNITA_ORGANIZZATIVE.ORDINAMENTO IS 'Stringa di ordinamento gerarchico';

COMMENT ON COLUMN RELAZIONI_UNITA_ORGANIZZATIVE.PROGR_PADRE_EFFETTIVO IS 'Progressivo del padre effettivo dell''unita''';



