CREATE TABLE SUDDIVISIONI_STRUTTURA
(
  ID_SUDDIVISIONE          NUMBER(8)            NOT NULL,
  OTTICA                   VARCHAR2(18 BYTE)    NOT NULL,
  SUDDIVISIONE             VARCHAR2(8 BYTE)     NOT NULL,
  DESCRIZIONE              VARCHAR2(60 BYTE)    NOT NULL,
  DESCRIZIONE_AL1          VARCHAR2(60 BYTE),
  DESCRIZIONE_AL2          VARCHAR2(60 BYTE),
  DES_ABB                  VARCHAR2(20 BYTE),
  DES_ABB_AL1              VARCHAR2(20 BYTE),
  DES_ABB_AL2              VARCHAR2(20 BYTE),
  ICONA_STANDARD           VARCHAR2(200 BYTE),
  BLOB_ICONA_STANDARD      BLOB                 DEFAULT EMPTY_BLOB(),
  ICONA_MODIFICA           VARCHAR2(200 BYTE),
  BLOB_ICONA_MODIFICA      BLOB                 DEFAULT EMPTY_BLOB(),
  ICONA_ELIMINAZIONE       VARCHAR2(200 BYTE),
  BLOB_ICONA_ELIMINAZIONE  BLOB                 DEFAULT EMPTY_BLOB(),
  NOTA                     VARCHAR2(2000 BYTE),
  UTENTE_AGGIORNAMENTO     VARCHAR2(8 BYTE),
  DATA_AGGIORNAMENTO       DATE,
  ORDINAMENTO              NUMBER(2)
)
TABLESPACE SO4
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            MAXSIZE          UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

COMMENT ON TABLE SUDDIVISIONI_STRUTTURA IS 'Specifica la descrizione delle suddivisioni (livelli) della struttura organizzativa';

COMMENT ON COLUMN SUDDIVISIONI_STRUTTURA.ID_SUDDIVISIONE IS 'Identificativo suddivisione';

COMMENT ON COLUMN SUDDIVISIONI_STRUTTURA.OTTICA IS 'Codice ottica';

COMMENT ON COLUMN SUDDIVISIONI_STRUTTURA.SUDDIVISIONE IS 'Codice suddivisione';

COMMENT ON COLUMN SUDDIVISIONI_STRUTTURA.DESCRIZIONE IS 'Descrizione suddivisione';

COMMENT ON COLUMN SUDDIVISIONI_STRUTTURA.DESCRIZIONE_AL1 IS 'Denominazione suddivisione in lingua alternativa 1';

COMMENT ON COLUMN SUDDIVISIONI_STRUTTURA.DESCRIZIONE_AL2 IS 'Denominazione suddivisione in lingua alternativa 2';

COMMENT ON COLUMN SUDDIVISIONI_STRUTTURA.DES_ABB IS 'Descrizione abbreviata';

COMMENT ON COLUMN SUDDIVISIONI_STRUTTURA.DES_ABB_AL1 IS 'Descrizione abbreviata in lingua alternativa 1';

COMMENT ON COLUMN SUDDIVISIONI_STRUTTURA.DES_ABB_AL2 IS 'Descrizione abbreviata in lingua alternativa 1';

COMMENT ON COLUMN SUDDIVISIONI_STRUTTURA.ICONA_STANDARD IS 'Icona associata alla suddivisione
';

COMMENT ON COLUMN SUDDIVISIONI_STRUTTURA.BLOB_ICONA_STANDARD IS 'Blob dell''icona associata alla suddivisione
';

COMMENT ON COLUMN SUDDIVISIONI_STRUTTURA.ICONA_MODIFICA IS 'Icona associata alla suddivisione in corso di modifica ';

COMMENT ON COLUMN SUDDIVISIONI_STRUTTURA.BLOB_ICONA_MODIFICA IS 'Blob dell''icona associata alla suddivisione in corso di modifica';

COMMENT ON COLUMN SUDDIVISIONI_STRUTTURA.ICONA_ELIMINAZIONE IS 'Icona associata alla suddivisione in corso di eliminazione
';

COMMENT ON COLUMN SUDDIVISIONI_STRUTTURA.BLOB_ICONA_ELIMINAZIONE IS 'Blob dell''icona associata alla suddivisione in corso di eliminazione';

COMMENT ON COLUMN SUDDIVISIONI_STRUTTURA.NOTA IS 'Nota suddivisione';

COMMENT ON COLUMN SUDDIVISIONI_STRUTTURA.UTENTE_AGGIORNAMENTO IS 'Utente ultimo aggiornamento';

COMMENT ON COLUMN SUDDIVISIONI_STRUTTURA.DATA_AGGIORNAMENTO IS 'Data ultimo aggiornamento';

COMMENT ON COLUMN SUDDIVISIONI_STRUTTURA.ORDINAMENTO IS 'Ordinamento nell''ambito della struttura';



