CREATE TABLE SUDDIVISIONI_FISICHE
(
  ID_SUDDIVISIONE       NUMBER(8)               NOT NULL,
  AMMINISTRAZIONE       VARCHAR2(50 BYTE)       NOT NULL,
  SUDDIVISIONE          VARCHAR2(8 BYTE)        NOT NULL,
  DENOMINAZIONE         VARCHAR2(60 BYTE)       NOT NULL,
  DENOMINAZIONE_AL1     VARCHAR2(60 BYTE),
  DENOMINAZIONE_AL2     VARCHAR2(60 BYTE),
  DES_ABB               VARCHAR2(20 BYTE),
  DES_ABB_AL1           VARCHAR2(20 BYTE),
  DES_ABB_AL2           VARCHAR2(20 BYTE),
  ICONA_STANDARD        VARCHAR2(120 BYTE),
  BLOB_ICONA_STANDARD   BLOB                    DEFAULT EMPTY_BLOB(),
  NOTA                  VARCHAR2(2000 BYTE),
  UTENTE_AGGIORNAMENTO  VARCHAR2(8 BYTE),
  DATA_AGGIORNAMENTO    DATE,
  ASSEGNABILE           VARCHAR2(2 BYTE)        DEFAULT 'SI',
  ORDINAMENTO           NUMBER(4)
)
TABLESPACE SO4
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            MAXSIZE          UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

COMMENT ON TABLE SUDDIVISIONI_FISICHE IS 'Anagrafica delle suddivisioni della struttura fisica';

COMMENT ON COLUMN SUDDIVISIONI_FISICHE.AMMINISTRAZIONE IS 'Codice dell''amministrazione a cui si riferisce la suddivisione';

COMMENT ON COLUMN SUDDIVISIONI_FISICHE.SUDDIVISIONE IS 'Codice suddivisione';

COMMENT ON COLUMN SUDDIVISIONI_FISICHE.DENOMINAZIONE IS 'Denominazione suddivisione';

COMMENT ON COLUMN SUDDIVISIONI_FISICHE.DENOMINAZIONE_AL1 IS 'Denominazione suddivisione in lingua alternativa 1';

COMMENT ON COLUMN SUDDIVISIONI_FISICHE.DENOMINAZIONE_AL2 IS 'Denominazione suddivisione in lingua alternativa 2';

COMMENT ON COLUMN SUDDIVISIONI_FISICHE.DES_ABB IS 'Descrizione abbreviata';

COMMENT ON COLUMN SUDDIVISIONI_FISICHE.DES_ABB_AL1 IS 'Descrizione abbreviata in lingua alternativa 1';

COMMENT ON COLUMN SUDDIVISIONI_FISICHE.DES_ABB_AL2 IS 'Descrizione abbreviata in lingua alternativa 2';

COMMENT ON COLUMN SUDDIVISIONI_FISICHE.ICONA_STANDARD IS 'Icona suddivisione';

COMMENT ON COLUMN SUDDIVISIONI_FISICHE.BLOB_ICONA_STANDARD IS 'Blob per l''icona della suddivisione
';

COMMENT ON COLUMN SUDDIVISIONI_FISICHE.NOTA IS 'Nota suddivisione';

COMMENT ON COLUMN SUDDIVISIONI_FISICHE.UTENTE_AGGIORNAMENTO IS 'Utente ultimo aggiornamento';

COMMENT ON COLUMN SUDDIVISIONI_FISICHE.DATA_AGGIORNAMENTO IS 'Data ultimo aggiornamento';

COMMENT ON COLUMN SUDDIVISIONI_FISICHE.ASSEGNABILE IS 'Valore di default per il campo Assegnabile delle UF di quella suddivisione';

COMMENT ON COLUMN SUDDIVISIONI_FISICHE.ORDINAMENTO IS 'Ordine gerarchico tra le suddivisioni fisiche';



