CREATE GLOBAL TEMPORARY TABLE TEMP_SO4
(
  TIPO_RECORD  VARCHAR2(2 BYTE),
  LIVELLO      NUMBER(3),
  PROGR_UO     NUMBER(8),
  CODICE_UO    VARCHAR2(50 BYTE),
  DESCR_UO     VARCHAR2(240 BYTE),
  NI_COMP      NUMBER(8),
  DESCR_COMP   VARCHAR2(240 BYTE)
)
ON COMMIT PRESERVE ROWS;


