CREATE GLOBAL TEMPORARY TABLE TEMP_STRUTTURA_SO4
(
  PROGR_UNITA_ORGANIZZATIVA  NUMBER(8),
  CODICE_UO                  VARCHAR2(50 BYTE),
  DESCRIZIONE_UO             VARCHAR2(240 BYTE),
  DAL                        DATE,
  AL                         DATE,
  ID_UNITA_PADRE             NUMBER(8)
)
ON COMMIT DELETE ROWS;


