CREATE TABLE TIPI_TITOLO
(
  TITOLO           VARCHAR2(4 BYTE)             NOT NULL,
  DESCRIZIONE      VARCHAR2(120 BYTE)           NOT NULL,
  DESCRIZIONE_AL1  VARCHAR2(120 BYTE),
  DESCRIZIONE_AL2  VARCHAR2(120 BYTE)
)
TABLESPACE SO4
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            MAXSIZE          UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

COMMENT ON COLUMN TIPI_TITOLO.DESCRIZIONE IS 'Descrizione titolo';



