CREATE TABLE WORK_RUBRICA
(
  NOMINATIVO         VARCHAR2(400 BYTE),
  AMMINISTRAZIONE    VARCHAR2(18 BYTE)          NOT NULL,
  DESCR_CONTATTO     VARCHAR2(240 BYTE),
  CONTATTO           VARCHAR2(240 BYTE),
  DESCR_UO           VARCHAR2(240 BYTE)         NOT NULL,
  TIPO_ASSEGNAZIONE  VARCHAR2(1 BYTE)           NOT NULL,
  DESCR_SEDE         VARCHAR2(240 BYTE),
  INDIRIZZO_SEDE     VARCHAR2(240 BYTE),
  DESCR_FIGURA       VARCHAR2(240 BYTE),
  DESCR_QUALIFICA    VARCHAR2(240 BYTE),
  DESCR_RAPPORTO     VARCHAR2(240 BYTE),
  RICERCA            VARCHAR2(4000 BYTE)        NOT NULL,
  TIPO               VARCHAR2(1 BYTE)           NOT NULL,
  NI                 NUMBER(8)                  NOT NULL,
  CONTATTO1          VARCHAR2(240 BYTE),
  CONTATTO2          VARCHAR2(240 BYTE)
)
TABLESPACE SO4
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            MAXSIZE          UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

COMMENT ON COLUMN WORK_RUBRICA.TIPO_ASSEGNAZIONE IS 'per esporre prima l''istituzionale e poi le funzionali';

COMMENT ON COLUMN WORK_RUBRICA.DESCR_SEDE IS 'sede di ubicazione fisica';

COMMENT ON COLUMN WORK_RUBRICA.INDIRIZZO_SEDE IS 'indirizzo composto della sede fisica';

COMMENT ON COLUMN WORK_RUBRICA.DESCR_FIGURA IS 'eventuale figura giuridica';

COMMENT ON COLUMN WORK_RUBRICA.DESCR_QUALIFICA IS 'eventuale qualifica economica';

COMMENT ON COLUMN WORK_RUBRICA.DESCR_RAPPORTO IS 'eventuale rapporto di lavoro';

COMMENT ON COLUMN WORK_RUBRICA.RICERCA IS 'concatenazione per ricerche';

COMMENT ON COLUMN WORK_RUBRICA.TIPO IS 'A assegnazione, C contatto';

COMMENT ON COLUMN WORK_RUBRICA.NI IS 'Soggetto';

COMMENT ON COLUMN WORK_RUBRICA.CONTATTO1 IS 'Contatto da esporre in griglia';

COMMENT ON COLUMN WORK_RUBRICA.CONTATTO2 IS 'Contatto da esporre in griglia';



