CREATE OR REPLACE FORCE VIEW DOCUMENTI
(ANNO, NUMERO, TIPO_REGISTRO, TIPO_DOCUMENTO, DATA_PROTOCOLLO, 
 MOVIMENTO, DATA_ARRIVO, MOD_RICEVIMENTO, NUMERO_DOCUMENTO, DATA_DOCUMENTO, 
 DATA_SCADENZA, DATA_EVASIONE, TIPO_STATO)
BEQUEATH DEFINER
AS 
select
ANNO,NUMERO,TIPO_REGISTRO,
TIPO_DOCUMENTO,DATA_PROTOCOLLO,
MOVIMENTO,DATA_ARRIVO,
MOD_RICEVIMENTO,
NUMERO_DOCUMENTO,DATA_DOCUMENTO,
DATA_SCADENZA,DATA_EVASIONE,TIPO_STATO 
from SO4_DOCUMENTI;


