CREATE OR REPLACE FORCE VIEW ENTI
(NI, DAL, COGNOME, NOME, SESSO, 
 DATA_NAS, PROVINCIA_NAS, COMUNE_NAS, LUOGO_NAS, CODICE_FISCALE, 
 CODICE_FISCALE_ESTERO, PARTITA_IVA, CITTADINANZA, GRUPPO_LING, INDIRIZZO_RES, 
 PROVINCIA_RES, COMUNE_RES, CAP_RES, TEL_RES, FAX_RES, 
 PRESSO, INDIRIZZO_DOM, PROVINCIA_DOM, COMUNE_DOM, CAP_DOM, 
 TEL_DOM, FAX_DOM, UTENTE, DATA_AGG, COMPETENZA, 
 COMPETENZA_ESCLUSIVA, TIPO_SOGGETTO, FLAG_TRG, STATO_CEE, PARTITA_IVA_CEE, 
 FINE_VALIDITA, AL, DENOMINAZIONE, INDIRIZZO_WEB, NOTE)
BEQUEATH DEFINER
AS 
SELECT NI
     , DAL
     , COGNOME
     , NOME
     , SESSO
     , DATA_NAS
     , PROVINCIA_NAS
     , COMUNE_NAS
     , LUOGO_NAS
     , CODICE_FISCALE
     , CODICE_FISCALE_ESTERO
     , PARTITA_IVA
     , CITTADINANZA
     , GRUPPO_LING
     , INDIRIZZO_RES
     , PROVINCIA_RES
     , COMUNE_RES
     , CAP_RES
     , TEL_RES
     , FAX_RES
     , PRESSO
     , INDIRIZZO_DOM
     , PROVINCIA_DOM
     , COMUNE_DOM
     , CAP_DOM
     , TEL_DOM
     , FAX_DOM
     , UTENTE
     , DATA_AGG
     , COMPETENZA
     , COMPETENZA_ESCLUSIVA
     , TIPO_SOGGETTO
     , FLAG_TRG
     , STATO_CEE
     , PARTITA_IVA_CEE
     , FINE_VALIDITA
     , AL
     , DENOMINAZIONE
     , INDIRIZZO_WEB
     , NOTE 
  FROM AS4_ANAGRAFE_SOGGETTI
 where nvl(tipo_soggetto,' ') = 'E';


