CREATE OR REPLACE FORCE VIEW KEY_NWORD
(TESTO, TRADUZIONE)
BEQUEATH DEFINER
AS 
select TESTO, TRADUZIONE
  from KEY_WORD
 where LINGUA = 'I';

COMMENT ON TABLE KEY_NWORD IS 'KEWO - Vista dei testi tradotti';



