CREATE OR REPLACE FORCE VIEW SI4_COMPETENZA_OGGETTI
(ID_COMPETENZA, ID_TIPO_OGGETTO, OGGETTO, UTENTE, ACCESSO, 
 NOMINATIVO_UTENTE, ID_TIPO_ABILITAZIONE, DAL, AL)
BEQUEATH DEFINER
AS 
select
   COMP.ID_COMPETENZA,
   ABIL.ID_TIPO_OGGETTO,
   COMP.OGGETTO,
   COMP.UTENTE,
   COMP.ACCESSO,
   UTEN.NOMINATIVO NOMINATIVO_UTENTE,
   ABIL.ID_TIPO_ABILITAZIONE,
   COMP.DAL,
   COMP.AL
from
   SI4_COMPETENZE COMP,
   SI4_ABILITAZIONI ABIL,
   AD4_UTENTI UTEN
where
   COMP.ID_ABILITAZIONE = ABIL.ID_ABILITAZIONE
   and COMP.UTENTE = UTEN.UTENTE;


