CREATE INDEX AMV_DIRI_UTEN_FK ON AMV_DIRITTI
(GRUPPO)
TABLESPACE SO4
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            MAXSIZE          UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );


