CREATE INDEX AMV_DIRI_AREE_FK ON AMV_DIRITTI
(ID_AREA)
TABLESPACE SO4
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            MAXSIZE          UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );


