CREATE UNIQUE INDEX AMV_DIRITTI_PK ON AMV_DIRITTI
(ID_DIRITTO)
TABLESPACE SO4
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            MAXSIZE          UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );


