CREATE UNIQUE INDEX AMV_RILEVANZE_PK ON AMV_RILEVANZE
(ID_RILEVANZA)
TABLESPACE SO4
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            MAXSIZE          UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );


