CREATE UNIQUE INDEX AMV_AREE_NOME_AK ON AMV_AREE
(NOME)
TABLESPACE SO4
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            MAXSIZE          UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );


