CREATE UNIQUE INDEX AMV_RILE_NOME_AK ON AMV_RILEVANZE
(NOME)
TABLESPACE SO4
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            MAXSIZE          UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );


