CREATE UNIQUE INDEX AMV_CLASSIFICAZIONI_PK ON AMV_CLASSIFICAZIONI
(ID_CLASSIFICAZIONE)
TABLESPACE SO4
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            MAXSIZE          UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );


