CREATE UNIQUE INDEX AMV_SEZIONI_PK ON AMV_SEZIONI
(ID_SEZIONE)
TABLESPACE SO4
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            MAXSIZE          UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );


