CREATE INDEX AMV_SEZI_AREE_FK ON AMV_SEZIONI
(ID_AREA)
TABLESPACE SO4
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            MAXSIZE          UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );


