CREATE INDEX AMV_DOCU_REVI_UTEN_APP ON AMV_DOCUMENTI_REVISIONI
(UTENTE_APPROVAZIONE)
TABLESPACE SO4
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            MAXSIZE          UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );


