CREATE INDEX AMV_DOCU_PADRE_IK ON AMV_DOCUMENTI
(ID_DOCUMENTO_PADRE)
TABLESPACE SO4
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            MAXSIZE          UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );


