CREATE INDEX AMV_CLAS_ARGO_FK ON AMV_CLASSIFICAZIONI
(ID_ARGOMENTO)
TABLESPACE SO4
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            MAXSIZE          UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );


