CREATE UNIQUE INDEX AMV_DOCUMENTI_REVISIONI_PK ON AMV_DOCUMENTI_REVISIONI
(ID_DOCUMENTO, REVISIONE)
TABLESPACE SO4
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            MAXSIZE          UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );


