CREATE UNIQUE INDEX AMV_ARGOMENTI_PK ON AMV_ARGOMENTI
(ID_ARGOMENTO)
TABLESPACE SO4
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            MAXSIZE          UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );


