CREATE UNIQUE INDEX AMV_BLOB_PK ON AMV_BLOB
(ID_BLOB)
TABLESPACE SO4
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            MAXSIZE          UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );


