CREATE INDEX ANAGRAFE_UNITA_FISICHE_IK ON ANAGRAFE_UNITA_FISICHE
(AMMINISTRAZIONE, DENOMINAZIONE)
TABLESPACE SO4
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            MAXSIZE          UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );


