CREATE INDEX ANUF_B_IK2 ON ANAGRAFE_UNITA_FISICHE_B
(AMMINISTRAZIONE, CODICE_UF)
TABLESPACE SO4
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            MAXSIZE          UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );


