CREATE INDEX ANUO_IK3 ON ANAGRAFE_UNITA_ORGANIZZATIVE
(DESCRIZIONE)
TABLESPACE SO4
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            MAXSIZE          UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );


