CREATE INDEX ANUO_IK5 ON ANAGRAFE_UNITA_ORGANIZZATIVE
(PROGR_UNITA_ORGANIZZATIVA, NVL("AL_PUBB",TO_DATE(' 4414-04-03 00:00:00', 'syyyy-mm-dd hh24:mi:ss')), DAL_PUBB)
TABLESPACE SO4
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            MAXSIZE          UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );


