CREATE INDEX ANUO_AK ON ANAGRAFE_UNITA_ORGANIZZATIVE
(CODICE_IPA)
TABLESPACE SO4
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            MAXSIZE          UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );


