CREATE INDEX ANUO_IK4 ON ANAGRAFE_UNITA_ORGANIZZATIVE
(PROGR_UNITA_ORGANIZZATIVA, OTTICA, DAL_PUBB)
TABLESPACE SO4
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            MAXSIZE          UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );


