CREATE INDEX ANUO_B_IK ON ANAGRAFE_UNITA_ORGANIZZATIVE_B
(PROGR_UNITA_ORGANIZZATIVA)
TABLESPACE SO4
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            MAXSIZE          UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );


