CREATE UNIQUE INDEX APPLICATIVI_PK ON APPLICATIVI
(ID_APPLICATIVO)
TABLESPACE SO4
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            MAXSIZE          UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );


