CREATE INDEX ASFI_B_IK1 ON ASSEGNAZIONI_FISICHE_B
(NI)
TABLESPACE SO4
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            MAXSIZE          UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );


