CREATE INDEX ASFI_B_IK2 ON ASSEGNAZIONI_FISICHE_B
(PROGR_UNITA_FISICA)
TABLESPACE SO4
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            MAXSIZE          UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );


