CREATE UNIQUE INDEX ASSEGNAZIONI_FISICHE_PK ON ASSEGNAZIONI_FISICHE
(ID_ASFI)
TABLESPACE SO4
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            MAXSIZE          UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );


