CREATE INDEX ASSEGNAZIONI_FISICHE_IK ON ASSEGNAZIONI_FISICHE
(NI)
TABLESPACE SO4
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            MAXSIZE          UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );


