CREATE UNIQUE INDEX ATAF_PK ON ATTRIBUTI_ASSEGNAZIONE_FISICA
(ID_ASFI, ATTRIBUTO, DAL)
TABLESPACE SO4
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            MAXSIZE          UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );


