CREATE INDEX ATCO_B_IK ON ATTRIBUTI_COMPONENTE_B
(ID_ATTR_COMPONENTE)
TABLESPACE SO4
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            MAXSIZE          UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );


