CREATE INDEX ATTRIBUTI_COMPONENTE_IK2 ON ATTRIBUTI_COMPONENTE
(ID_COMPONENTE, DAL_PUBB)
TABLESPACE SO4
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            MAXSIZE          UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );


