CREATE UNIQUE INDEX ATTRIBUTI_COMPONENTE_PK ON ATTRIBUTI_COMPONENTE
(ID_ATTR_COMPONENTE)
TABLESPACE SO4
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            MAXSIZE          UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );


