CREATE UNIQUE INDEX ATTRIBUTI_STILE_PK ON ATTRIBUTI_STILE
(STILE, ATTRIBUTO)
TABLESPACE SO4
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            MAXSIZE          UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );


