CREATE INDEX ATTRIBUTI_COMPONENTE_IK ON ATTRIBUTI_COMPONENTE
(ID_COMPONENTE, DAL)
TABLESPACE SO4
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            MAXSIZE          UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );


