CREATE UNIQUE INDEX ATTRIBUTI_UNITA_FISICA_SO_PK ON ATTRIBUTI_UNITA_FISICA_SO
(PROGR_UNITA_FISICA, ATTRIBUTO, DAL)
TABLESPACE SO4
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            MAXSIZE          UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );


