CREATE INDEX CATEGORIE_MODIFICHE_IK3 ON SO4_EVENTI
(ID_MODIFICA)
TABLESPACE SO4
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            MAXSIZE          UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );


