CREATE INDEX CATEGORIE_MODIFICHE_IK ON SO4_EVENTI
(OGGETTO)
TABLESPACE SO4
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            MAXSIZE          UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );


