CREATE INDEX CATEGORIE_MODIFICHE_IK2 ON SO4_EVENTI
(CATEGORIA)
TABLESPACE SO4
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            MAXSIZE          UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );


