CREATE UNIQUE INDEX COMPETENZE_DELEGA_PK ON COMPETENZE_DELEGA
(ID_COMPETENZA_DELEGA)
TABLESPACE SO4
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            MAXSIZE          UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );


