CREATE INDEX DELE_CODE_FK ON DELEGHE
(ID_COMPETENZA_DELEGA)
TABLESPACE SO4
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            MAXSIZE          UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );


