CREATE UNIQUE INDEX EXTERNAL_FUNCTIONS_PK ON EXTERNAL_FUNCTIONS
(FUNCTION_ID)
TABLESPACE SO4
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            MAXSIZE          UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );


