CREATE INDEX IMBI_B_IK ON IMPUTAZIONI_BILANCIO_B
(ID_IMPUTAZIONE)
TABLESPACE SO4
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            MAXSIZE          UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );


