CREATE UNIQUE INDEX IMPUTAZIONI_BILANCIO_PK ON IMPUTAZIONI_BILANCIO
(ID_IMPUTAZIONE)
TABLESPACE SO4
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            MAXSIZE          UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );


