CREATE UNIQUE INDEX IMPUTAZIONI_BILANCIO_B_PK ON IMPUTAZIONI_BILANCIO_B
(ID_BACKUP)
TABLESPACE SO4
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            MAXSIZE          UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );


