CREATE UNIQUE INDEX INDIRIZZI_TELEMATICI_PK ON INDIRIZZI_TELEMATICI
(ID_INDIRIZZO)
TABLESPACE SO4
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            MAXSIZE          UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );


