CREATE INDEX ISPU_AK ON ISCRIZIONI_PUBBLICAZIONE
(AMMINISTRAZIONE, OTTICA, CATEGORIA, MODIFICA)
TABLESPACE SO4
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            MAXSIZE          UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );


