CREATE UNIQUE INDEX ISPU_PK ON ISCRIZIONI_PUBBLICAZIONE
(ID_ISCRIZIONE)
TABLESPACE SO4
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            MAXSIZE          UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );


