CREATE INDEX ISPU_IK2 ON ISCRIZIONI_PUBBLICAZIONE
(CATEGORIA)
TABLESPACE SO4
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            MAXSIZE          UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );


