CREATE INDEX ISPU_IK1 ON ISCRIZIONI_PUBBLICAZIONE
(MODULO)
TABLESPACE SO4
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            MAXSIZE          UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );


