CREATE UNIQUE INDEX KCCO_PK ON KEY_CONSTRAINT_COLUMN
(NOME, COLONNA)
TABLESPACE SO4
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            MAXSIZE          UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );


