CREATE UNIQUE INDEX KECO_UK ON KEY_CONSTRAINT
(OGGETTO, TIPO, SEQUENZA)
TABLESPACE SO4
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            MAXSIZE          UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );


