CREATE UNIQUE INDEX KEDI_PK ON KEY_DICTIONARY
(TABELLA, COLONNA, PK, LINGUA)
TABLESPACE SO4
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            MAXSIZE          UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );


