CREATE UNIQUE INDEX KEEL_PK ON KEY_ERROR_LOG
(ERROR_ID)
TABLESPACE SO4
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            MAXSIZE          UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );


