CREATE UNIQUE INDEX MODIFICHE_COMPONENTI_PK ON MODIFICHE_COMPONENTI
(ID_MODIFICA)
TABLESPACE SO4
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            MAXSIZE          UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );


