CREATE INDEX MODIFICHE_COMPONENTI_IK1 ON MODIFICHE_COMPONENTI
(ID_COMPONENTE)
TABLESPACE SO4
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            MAXSIZE          UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );


