CREATE UNIQUE INDEX OPERAZIONI_DERIVATE_PK ON OPERAZIONI_DERIVATE
(ID_MODIFICA, OTTICA)
TABLESPACE SO4
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            MAXSIZE          UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );


