CREATE UNIQUE INDEX OTTICHE_UK ON OTTICHE
(AMMINISTRAZIONE, DESCRIZIONE)
TABLESPACE SO4
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            MAXSIZE          UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );


