CREATE INDEX OTTI_B_UK ON OTTICHE_B
(AMMINISTRAZIONE, DESCRIZIONE)
TABLESPACE SO4
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            MAXSIZE          UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );


