CREATE UNIQUE INDEX PAFU_PK ON PARAMETRI_FUNZIONE
(ID_PARAMETRO_FUNZIONE)
TABLESPACE SO4
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            MAXSIZE          UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );


