CREATE INDEX PARAMETRI_FUNZIONE_AK ON PARAMETRI_FUNZIONE
(ID_FUNZIONE)
TABLESPACE SO4
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            MAXSIZE          UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );


