CREATE INDEX RELAZIONI_UO_IK1 ON RELAZIONI_UNITA_ORGANIZZATIVE
(OTTICA, PROGR_PADRE)
TABLESPACE SO4
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            MAXSIZE          UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );


