CREATE INDEX RELAZIONI_UO_IK5 ON RELAZIONI_UNITA_ORGANIZZATIVE
(OTTICA, REVISIONE)
TABLESPACE SO4
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            MAXSIZE          UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );


