CREATE UNIQUE INDEX RELAZIONI_INDIRIZZO_CONT_PK ON RELAZIONI_INDIRIZZO_CONTATTO
(TIPO_INDIRIZZO, TIPO_CONTATTO)
TABLESPACE SO4
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );


