CREATE INDEX REST_B_IK ON REVISIONI_STRUTTURA_B
(OTTICA, REVISIONE)
TABLESPACE SO4
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            MAXSIZE          UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );


