CREATE UNIQUE INDEX REVISIONI_STRUTTURA_PK ON REVISIONI_STRUTTURA
(STATO, OTTICA, REVISIONE)
TABLESPACE SO4
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            MAXSIZE          UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );


