CREATE UNIQUE INDEX REVISIONI_STRUTTURA_UK ON REVISIONI_STRUTTURA
(OTTICA, DESCRIZIONE)
TABLESPACE SO4
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            MAXSIZE          UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );


