CREATE UNIQUE INDEX REVISIONI_STRUTTURA_B_PK ON REVISIONI_STRUTTURA_B
(ID_BACKUP)
TABLESPACE SO4
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            MAXSIZE          UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );


