CREATE UNIQUE INDEX RUDE_PK ON RUOLI_DERIVATI
(ID_RUOLO_DERIVATO)
TABLESPACE SO4
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            MAXSIZE          UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );


