CREATE INDEX RUDE_PROF_FK ON RUOLI_DERIVATI
(ID_PROFILO)
TABLESPACE SO4
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            MAXSIZE          UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );


