CREATE UNIQUE INDEX RUOLI_PROFILO_PK ON RUOLI_PROFILO
(ID_RUOLO_PROFILO)
TABLESPACE SO4
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            MAXSIZE          UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );


