CREATE INDEX RUOLI_COMPONENT_IK2 ON RUOLI_COMPONENTE
(ID_COMPONENTE, DAL_PUBB, RUOLO)
TABLESPACE SO4
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            MAXSIZE          UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );


