CREATE INDEX SI4_COMP_ABIL_FK ON SI4_COMPETENZE
(ID_ABILITAZIONE)
TABLESPACE SO4
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            MAXSIZE          UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );


