CREATE UNIQUE INDEX SI4_FUNZIONI_PK ON SI4_FUNZIONI
(ID_FUNZIONE)
TABLESPACE SO4
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            MAXSIZE          UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );


