CREATE INDEX SI4_COMP_OGGETTO ON SI4_COMPETENZE
(TIPO_COMPETENZA, OGGETTO)
TABLESPACE SO4
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            MAXSIZE          UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );


