CREATE UNIQUE INDEX SI4_TIPI_ABILITAZIONE_PK ON SI4_TIPI_ABILITAZIONE
(ID_TIPO_ABILITAZIONE)
TABLESPACE SO4
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );


