CREATE UNIQUE INDEX SO4_CODIFICHE_UK ON SO4_CODIFICHE
(DOMINIO, VALORE)
TABLESPACE SO4
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            MAXSIZE          UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );


