CREATE UNIQUE INDEX SOAO_PK ON SOGGETTI_AOO
(PROGR_AOO)
TABLESPACE SO4
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            MAXSIZE          UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );


