CREATE UNIQUE INDEX SOGGETTI_RUBRICA_PK ON SOGGETTI_RUBRICA
(NI, TIPO_CONTATTO, PROGRESSIVO)
TABLESPACE SO4
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            MAXSIZE          UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );


