CREATE UNIQUE INDEX SUDDIVISIONI_STRUTTURA_PK ON SUDDIVISIONI_STRUTTURA
(ID_SUDDIVISIONE)
TABLESPACE SO4
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            MAXSIZE          UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );


