CREATE INDEX TASK_FUNZIONI_AK1 ON TASK_FUNZIONI
(ID_FUNZIONE)
TABLESPACE SO4
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            MAXSIZE          UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );


