CREATE UNIQUE INDEX TIPI_TITOLO_PK ON TIPI_TITOLO
(TITOLO)
TABLESPACE SO4
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            MAXSIZE          UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );


