CREATE INDEX UBCO_B_IK2 ON UBICAZIONI_COMPONENTE_B
(ID_UBICAZIONE_COMPONENTE)
TABLESPACE SO4
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            MAXSIZE          UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );


