CREATE UNIQUE INDEX UBICAZIONI_UNITA_PK ON UBICAZIONI_UNITA
(ID_UBICAZIONE)
TABLESPACE SO4
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            MAXSIZE          UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );


