CREATE UNIQUE INDEX UBICAZIONI_COMPONENTE_UK ON UBICAZIONI_COMPONENTE
(ID_COMPONENTE, DAL)
TABLESPACE SO4
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            MAXSIZE          UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );


