CREATE INDEX UNFI_B_IK2 ON UNITA_FISICHE_B
(ID_UNITA_FISICA_PADRE)
TABLESPACE SO4
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            MAXSIZE          UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );


