CREATE INDEX UNFI_B_IK3 ON UNITA_FISICHE_B
(AMMINISTRAZIONE, PROGR_UNITA_FISICA)
TABLESPACE SO4
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            MAXSIZE          UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );


