CREATE INDEX UNITA_ORGANIZZATIVE_IK ON UNITA_ORGANIZZATIVE
(OTTICA, PROGR_UNITA_ORGANIZZATIVA, DAL)
TABLESPACE SO4
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            MAXSIZE          UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );


