CREATE UNIQUE INDEX UNITA_FISICHE_PK ON UNITA_FISICHE
(ID_ELEMENTO_FISICO)
TABLESPACE SO4
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            MAXSIZE          UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );


