CREATE UNIQUE INDEX UNITA_ORGANIZZATIVE_PK ON UNITA_ORGANIZZATIVE
(ID_ELEMENTO)
TABLESPACE SO4
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            MAXSIZE          UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );


