CREATE INDEX UNOR_B_IK ON UNITA_ORGANIZZATIVE_B
(OTTICA, PROGR_UNITA_ORGANIZZATIVA)
TABLESPACE SO4
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            MAXSIZE          UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );


