CREATE UNIQUE INDEX WORK_REVISIONI_PK ON WORK_REVISIONI
(ID_WORK_REVISIONE)
TABLESPACE SO4
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            MAXSIZE          UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );


