CREATE INDEX WORK_ALUO_AK ON WORK_ALLINEA_UNITA
(OTTICA, AL, LIVELLO)
TABLESPACE SO4
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            MAXSIZE          UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );


