CREATE INDEX WORU_IK ON WORK_RUBRICA
(RICERCA)
TABLESPACE SO4
PCTFREE    10
INITRANS   2
MAXTRANS   167
STORAGE    (
            MAXSIZE          UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );


