ALTER TABLE AMMINISTRAZIONI ADD (
  CONSTRAINT AMMINISTRAZIO_ENTE_CC
  CHECK (ENTE in ('SI','NO'))
  ENABLE VALIDATE);

ALTER TABLE AMMINISTRAZIONI ADD (
  CONSTRAINT AMMINISTRAZIONI_PK
  PRIMARY KEY
  (CODICE_AMMINISTRAZIONE)
  USING INDEX AMMINISTRAZIONI_PK
  ENABLE VALIDATE);

