ALTER TABLE AMV_ABILITAZIONI ADD (
  CONSTRAINT AMV_ABIL_MENU_FK 
  FOREIGN KEY (PADRE, RUOLO) 
  REFERENCES AMV_ABILITAZIONI (ABILITAZIONE,RUOLO)
  ON DELETE CASCADE
  ENABLE VALIDATE);

ALTER TABLE AMV_ABILITAZIONI ADD (
  CONSTRAINT AMV_ABIL_MODU_FK 
  FOREIGN KEY (MODULO) 
  REFERENCES AD4.MODULI (MODULO)
  ENABLE VALIDATE);

ALTER TABLE AMV_ABILITAZIONI ADD (
  CONSTRAINT AMV_ABIL_RUOL_FK 
  FOREIGN KEY (RUOLO) 
  REFERENCES AD4.RUOLI (RUOLO)
  ENABLE VALIDATE);

ALTER TABLE AMV_ABILITAZIONI ADD (
  CONSTRAINT AMV_ABIL_VOCI_FK 
  FOREIGN KEY (VOCE_MENU) 
  REFERENCES AMV_VOCI (VOCE)
  ENABLE VALIDATE);

