ALTER TABLE AMV_CLASSIFICAZIONI ADD (
  CONSTRAINT AMV_CLASSIFIC_ID_ARGOMENTO_CC
  CHECK (ID_ARGOMENTO >= 1)
  ENABLE VALIDATE);

ALTER TABLE AMV_CLASSIFICAZIONI ADD (
  CONSTRAINT AMV_CLASSIFIC_ID_CATEGORIA_CC
  CHECK (ID_CATEGORIA >= 1)
  ENABLE VALIDATE);

ALTER TABLE AMV_CLASSIFICAZIONI ADD (
  CONSTRAINT AMV_CLASSIFIC_ID_CLASSIFICA_CC
  CHECK (ID_CLASSIFICAZIONE >= 1)
  ENABLE VALIDATE);

ALTER TABLE AMV_CLASSIFICAZIONI ADD (
  CONSTRAINT AMV_CLASSIFICAZIONI_PK
  PRIMARY KEY
  (ID_CLASSIFICAZIONE)
  USING INDEX AMV_CLASSIFICAZIONI_PK
  ENABLE VALIDATE);

