ALTER TABLE AMV_ARGOMENTI ADD (
  CONSTRAINT AMV_ARGOMENTI_ID_ARGOMENTO_CC
  CHECK (ID_ARGOMENTO >= 1)
  ENABLE VALIDATE);

ALTER TABLE AMV_ARGOMENTI ADD (
  CONSTRAINT AMV_ARGOMENTI_PK
  PRIMARY KEY
  (ID_ARGOMENTO)
  USING INDEX AMV_ARGOMENTI_PK
  ENABLE VALIDATE);

ALTER TABLE AMV_ARGOMENTI ADD (
  CONSTRAINT AMV_ARGO_NOME_AK
  UNIQUE (NOME)
  USING INDEX AMV_ARGO_NOME_AK
  ENABLE VALIDATE);

