ALTER TABLE AMV_SEZIONI ADD (
  CONSTRAINT AMV_SEZIONI_VISIBILITA_CC
  CHECK (VISIBILITA is null or ( VISIBILITA in ('N','T','I') ))
  ENABLE VALIDATE);

ALTER TABLE AMV_SEZIONI ADD (
  CONSTRAINT AMV_SEZIONI_ZONA_CC
  CHECK (ZONA is null or ( ZONA in ('S','C','D','A') ))
  ENABLE VALIDATE);

ALTER TABLE AMV_SEZIONI ADD (
  CONSTRAINT AMV_SEZIONI_ZONA_ESPANSIO_CC
  CHECK (ZONA_ESPANSIONE is null or ( ZONA_ESPANSIONE in ('S','N') ))
  ENABLE VALIDATE);

ALTER TABLE AMV_SEZIONI ADD (
  CONSTRAINT AMV_SEZIONI_ZONA_FORMATO_CC
  CHECK (ZONA_FORMATO is null or ( ZONA_FORMATO in ('T','I') ))
  ENABLE VALIDATE);

ALTER TABLE AMV_SEZIONI ADD (
  CONSTRAINT AMV_SEZIONI_ZONA_TIPO_CC
  CHECK (ZONA_TIPO is null or ( ZONA_TIPO in ('D','S','E') ))
  ENABLE VALIDATE);

ALTER TABLE AMV_SEZIONI ADD (
  CONSTRAINT AMV_SEZIONI_ZONA_VISIBILI_CC
  CHECK (ZONA_VISIBILITA is null or ( ZONA_VISIBILITA in ('S','H','C','E') ))
  ENABLE VALIDATE);

ALTER TABLE AMV_SEZIONI ADD (
  CONSTRAINT AMV_SEZIONI_PK
  PRIMARY KEY
  (ID_SEZIONE)
  USING INDEX AMV_SEZIONI_PK
  ENABLE VALIDATE);

