ALTER TABLE AMV_VOCI ADD (
  CONSTRAINT AMV_VOCI_TIPO_CC
  CHECK (TIPO in ('M','C','N','E','F','Q','D','L','A'))
  ENABLE VALIDATE);

ALTER TABLE AMV_VOCI ADD (
  CONSTRAINT AMV_VOCI_TIPO_VOCE_CC
  CHECK (TIPO_VOCE in ('N','F','A'))
  ENABLE VALIDATE);

ALTER TABLE AMV_VOCI ADD (
  CONSTRAINT AMV_VOCI_PK
  PRIMARY KEY
  (VOCE)
  USING INDEX AMV_VOCI_PK
  ENABLE VALIDATE);

