ALTER TABLE AMV_GUIDE ADD (
  CONSTRAINT AMV_GUID_VOCI_FK 
  FOREIGN KEY (GUIDA) 
  REFERENCES AMV_VOCI (VOCE)
  ON DELETE CASCADE
  ENABLE VALIDATE);

ALTER TABLE AMV_GUIDE ADD (
  CONSTRAINT AMV_GUID_VOCI_GUI_FK 
  FOREIGN KEY (VOCE_GUIDA) 
  REFERENCES AMV_VOCI (VOCE)
  ENABLE VALIDATE);

ALTER TABLE AMV_GUIDE ADD (
  CONSTRAINT AMV_GUID_VOCI_MEN_FK 
  FOREIGN KEY (VOCE_MENU) 
  REFERENCES AMV_VOCI (VOCE)
  ENABLE VALIDATE);

ALTER TABLE AMV_GUIDE ADD (
  CONSTRAINT AMV_GUID_VOCI_RIF_FK 
  FOREIGN KEY (VOCE_RIF) 
  REFERENCES AMV_VOCI (VOCE)
  ENABLE VALIDATE);

