ALTER TABLE AMV_AREE ADD (
  CONSTRAINT AMV_AREE_ID_AREA_CC
  CHECK (ID_AREA >= 1)
  ENABLE VALIDATE);

ALTER TABLE AMV_AREE ADD (
  CONSTRAINT AMV_AREE_PK
  PRIMARY KEY
  (ID_AREA)
  USING INDEX AMV_AREE_PK
  ENABLE VALIDATE);

ALTER TABLE AMV_AREE ADD (
  CONSTRAINT AMV_AREE_NOME_AK
  UNIQUE (NOME)
  USING INDEX AMV_AREE_NOME_AK
  ENABLE VALIDATE);

