ALTER TABLE AMV_TIPOLOGIE ADD (
  CONSTRAINT AMV_TIPO_FOR_CC
  CHECK (ZONA_FORMATO is null or ( ZONA_FORMATO in ('T','I') ))
  ENABLE VALIDATE);

ALTER TABLE AMV_TIPOLOGIE ADD (
  CONSTRAINT AMV_TIPOLOGIE_ID_TIPOLOGIA_CC
  CHECK (ID_TIPOLOGIA >= 1)
  ENABLE VALIDATE);

ALTER TABLE AMV_TIPOLOGIE ADD (
  CONSTRAINT AMV_TIPOLOGIE_ZONA_CC
  CHECK (ZONA is null or ( ZONA in ('A','S','D','C') ))
  ENABLE VALIDATE);

ALTER TABLE AMV_TIPOLOGIE ADD (
  CONSTRAINT AMV_TIPO_ZONA_VISIB_CC
  CHECK (ZONA_VISIBILITA is null or ( ZONA_VISIBILITA in ('S','H','C') ))
  ENABLE VALIDATE);

ALTER TABLE AMV_TIPOLOGIE ADD (
  CONSTRAINT AMV_TIPOLOGIE_PK
  PRIMARY KEY
  (ID_TIPOLOGIA)
  USING INDEX AMV_TIPOLOGIE_PK
  ENABLE VALIDATE);

ALTER TABLE AMV_TIPOLOGIE ADD (
  CONSTRAINT AMV_TIPO_NOME_AK
  UNIQUE (NOME)
  USING INDEX AMV_TIPO_NOME_AK
  ENABLE VALIDATE);

