ALTER TABLE AMV_DOCUMENTI ADD (
  CONSTRAINT AMV_DOCU_AREE_FK 
  FOREIGN KEY (ID_AREA) 
  REFERENCES AMV_AREE (ID_AREA)
  ENABLE VALIDATE);

ALTER TABLE AMV_DOCUMENTI ADD (
  CONSTRAINT AMV_DOCU_ARGO_FK 
  FOREIGN KEY (ID_ARGOMENTO) 
  REFERENCES AMV_ARGOMENTI (ID_ARGOMENTO)
  ENABLE VALIDATE);

ALTER TABLE AMV_DOCUMENTI ADD (
  CONSTRAINT AMV_DOCU_CATE_FK 
  FOREIGN KEY (ID_CATEGORIA) 
  REFERENCES AMV_CATEGORIE (ID_CATEGORIA)
  ENABLE VALIDATE);

ALTER TABLE AMV_DOCUMENTI ADD (
  CONSTRAINT AMV_DOCU_DOCU_FK 
  FOREIGN KEY (ID_DOCUMENTO_PADRE, REVISIONE) 
  REFERENCES AMV_DOCUMENTI (ID_DOCUMENTO,REVISIONE)
  ENABLE VALIDATE);

ALTER TABLE AMV_DOCUMENTI ADD (
  CONSTRAINT AMV_DOCU_RILE_FK 
  FOREIGN KEY (ID_RILEVANZA) 
  REFERENCES AMV_RILEVANZE (ID_RILEVANZA)
  ENABLE VALIDATE);

ALTER TABLE AMV_DOCUMENTI ADD (
  CONSTRAINT AMV_DOCU_SEZI_FK 
  FOREIGN KEY (ID_SEZIONE) 
  REFERENCES AMV_SEZIONI (ID_SEZIONE)
  ENABLE VALIDATE);

ALTER TABLE AMV_DOCUMENTI ADD (
  CONSTRAINT AMV_DOCU_TIPO_FK 
  FOREIGN KEY (ID_TIPOLOGIA) 
  REFERENCES AMV_TIPOLOGIE (ID_TIPOLOGIA)
  ENABLE VALIDATE);

