ALTER TABLE AMV_CATEGORIE ADD (
  CONSTRAINT AMV_CATEGORIE_ID_CATEGORIA_CC
  CHECK (ID_CATEGORIA >= 1)
  ENABLE VALIDATE);

ALTER TABLE AMV_CATEGORIE ADD (
  CONSTRAINT AMV_CATEGORIE_PK
  PRIMARY KEY
  (ID_CATEGORIA)
  USING INDEX AMV_CATEGORIE_PK
  ENABLE VALIDATE);

ALTER TABLE AMV_CATEGORIE ADD (
  CONSTRAINT AMV_CATE_NOME_AK
  UNIQUE (NOME)
  USING INDEX AMV_CATE_NOME_AK
  ENABLE VALIDATE);

