ALTER TABLE AMV_CLASSIFICAZIONI ADD (
  CONSTRAINT AMV_CLAS_ARGO_FK 
  FOREIGN KEY (ID_ARGOMENTO) 
  REFERENCES AMV_ARGOMENTI (ID_ARGOMENTO)
  ENABLE VALIDATE);

ALTER TABLE AMV_CLASSIFICAZIONI ADD (
  CONSTRAINT AMV_CLAS_CATE_FK 
  FOREIGN KEY (ID_CATEGORIA) 
  REFERENCES AMV_CATEGORIE (ID_CATEGORIA)
  ENABLE VALIDATE);

