ALTER TABLE AMV_DOCUMENTI ADD (
  CONSTRAINT AMV_DOCUMENTI_ID_AREA_CC
  CHECK (ID_AREA >= 1)
  ENABLE VALIDATE);

ALTER TABLE AMV_DOCUMENTI ADD (
  CONSTRAINT AMV_DOCUMENTI_ID_ARGOMENTO_CC
  CHECK (ID_ARGOMENTO >= 1)
  ENABLE VALIDATE);

ALTER TABLE AMV_DOCUMENTI ADD (
  CONSTRAINT AMV_DOCUMENTI_ID_DOCUMENTO_CC
  CHECK (ID_DOCUMENTO >= 1)
  ENABLE VALIDATE);

ALTER TABLE AMV_DOCUMENTI ADD (
  CONSTRAINT AMV_DOCUMENTI_ID_PADRE_CC
  CHECK (ID_DOCUMENTO_PADRE is null or (ID_DOCUMENTO_PADRE >= 1 ))
  ENABLE VALIDATE);

ALTER TABLE AMV_DOCUMENTI ADD (
  CONSTRAINT AMV_DOCUMENTI_ID_RILEVANZA_CC
  CHECK (ID_RILEVANZA >= 1)
  ENABLE VALIDATE);

ALTER TABLE AMV_DOCUMENTI ADD (
  CONSTRAINT AMV_DOCUMENTI_PK
  PRIMARY KEY
  (ID_DOCUMENTO, REVISIONE)
  USING INDEX AMV_DOCUMENTI_PK
  ENABLE VALIDATE);

