ALTER TABLE AMV_DIRITTI ADD (
  CONSTRAINT AMV_DIRI_AREE_FK 
  FOREIGN KEY (ID_AREA) 
  REFERENCES AMV_AREE (ID_AREA)
  ENABLE VALIDATE);

ALTER TABLE AMV_DIRITTI ADD (
  CONSTRAINT AMV_DIRI_TIPO_FK 
  FOREIGN KEY (ID_TIPOLOGIA) 
  REFERENCES AMV_TIPOLOGIE (ID_TIPOLOGIA)
  ENABLE VALIDATE);

