ALTER TABLE ANAGRAFE_UNITA_ORGANIZZATIVE ADD (
  CONSTRAINT ANAGRAFE_UNIT_ASSEGNAZIONE__CC
  CHECK (ASSEGNAZIONE_COMPONENTI is null or ( ASSEGNAZIONE_COMPONENTI in ('SI','NO') ))
  ENABLE VALIDATE);

ALTER TABLE ANAGRAFE_UNITA_ORGANIZZATIVE ADD (
  CONSTRAINT ANAGRAFE_UNIT_CENTRO_RESPON_CC
  CHECK (CENTRO_RESPONSABILITA is null or ( CENTRO_RESPONSABILITA in ('SI','NO') ))
  ENABLE VALIDATE);

ALTER TABLE ANAGRAFE_UNITA_ORGANIZZATIVE ADD (
  CONSTRAINT ANAGRAFE_UNIT_CODICE_UO_CC
  CHECK (CODICE_UO = upper(CODICE_UO))
  ENABLE VALIDATE);

ALTER TABLE ANAGRAFE_UNITA_ORGANIZZATIVE ADD (
  CONSTRAINT ANAGRAFE_UNIT_SE_FATTURA_EL_CC
  CHECK (SE_FATTURA_ELETTRONICA is null or (SE_FATTURA_ELETTRONICA in ('SI','NO')))
  ENABLE VALIDATE);

ALTER TABLE ANAGRAFE_UNITA_ORGANIZZATIVE ADD (
  CONSTRAINT ANAGRAFE_UNIT_SE_GIURIDICO_CC
  CHECK (SE_GIURIDICO is null or ( SE_GIURIDICO in ('SI','NO') ))
  ENABLE VALIDATE);

ALTER TABLE ANAGRAFE_UNITA_ORGANIZZATIVE ADD (
  CONSTRAINT ANAGRAFE_UNIT_TIPOLOGIA_UNI_CC
  CHECK (TIPOLOGIA_UNITA is null or (TIPOLOGIA_UNITA = upper(TIPOLOGIA_UNITA)))
  ENABLE VALIDATE);

ALTER TABLE ANAGRAFE_UNITA_ORGANIZZATIVE ADD (
  CONSTRAINT ANAGRAFE_UNIT_TIPO_UNITA_CC
  CHECK (TIPO_UNITA is null or (TIPO_UNITA in ('A','P','S')))
  ENABLE VALIDATE);

ALTER TABLE ANAGRAFE_UNITA_ORGANIZZATIVE ADD (
  CONSTRAINT ANUO_PK
  PRIMARY KEY
  (PROGR_UNITA_ORGANIZZATIVA, DAL)
  USING INDEX ANUO_PK
  ENABLE VALIDATE);

