ALTER TABLE ATTRIBUTI_COMPONENTE ADD (
  CONSTRAINT ATTRIBUTI_COM_TIPO_ASSEGNAZ_CC
  CHECK (TIPO_ASSEGNAZIONE is null or ( TIPO_ASSEGNAZIONE in ('I','F') ))
  ENABLE VALIDATE);

ALTER TABLE ATTRIBUTI_COMPONENTE ADD (
  CONSTRAINT ATTRIBUTI_COMPONENTE_PK
  PRIMARY KEY
  (ID_ATTR_COMPONENTE)
  USING INDEX ATTRIBUTI_COMPONENTE_PK
  ENABLE VALIDATE);

