ALTER TABLE ATTRIBUTI_UNITA_FISICA_SO ADD (
  CONSTRAINT ATTRIBUTI_UNITA_FISICA_SO_PK
  PRIMARY KEY
  (PROGR_UNITA_FISICA, ATTRIBUTO, DAL)
  USING INDEX ATTRIBUTI_UNITA_FISICA_SO_PK
  ENABLE VALIDATE);

