ALTER TABLE CODICI_IPA ADD (
  CONSTRAINT CODICI_IPA_TIPO_CC
  CHECK (tipo_entita in ('AM','AO','UO'))
  ENABLE VALIDATE);

ALTER TABLE CODICI_IPA ADD (
  CONSTRAINT COIP_PK
  PRIMARY KEY
  (TIPO_ENTITA, PROGRESSIVO)
  USING INDEX COIP_PK
  ENABLE VALIDATE);

