ALTER TABLE COMPONENTI ADD (
  CONSTRAINT COMPONENTI_STATO_CC
  CHECK (STATO is null or ( STATO in ('P','D') ))
  ENABLE VALIDATE);

ALTER TABLE COMPONENTI ADD (
  CONSTRAINT COMPONENTI_PK
  PRIMARY KEY
  (ID_COMPONENTE)
  USING INDEX COMPONENTI_PK
  ENABLE VALIDATE);

