ALTER TABLE EXTERNAL_FUNCTIONS ADD (
  CONSTRAINT EXTERNAL_FUNC_FIRING_EVENT_CC
  CHECK (FIRING_EVENT in ('I','U','D'))
  ENABLE VALIDATE);

ALTER TABLE EXTERNAL_FUNCTIONS ADD (
  CONSTRAINT EXTERNAL_FUNCTIONS_PK
  PRIMARY KEY
  (FUNCTION_ID)
  USING INDEX EXTERNAL_FUNCTIONS_PK
  ENABLE VALIDATE);

