ALTER TABLE IMPOSTAZIONI_TABLE ADD (
  CONSTRAINT IMPOSTAZIONI_AGG_ANAGRAFE__CC
  CHECK (AGG_ANAGRAFE_DIPENDENTI is null or ( AGG_ANAGRAFE_DIPENDENTI in ('SI','NO') ))
  ENABLE VALIDATE);

ALTER TABLE IMPOSTAZIONI_TABLE ADD (
  CONSTRAINT IMPOSTAZIONI_ASSEGNAZIONE__CC
  CHECK (ASSEGNAZIONE_DEFINITIVA in ('SI','NO'))
  ENABLE VALIDATE);

ALTER TABLE IMPOSTAZIONI_TABLE ADD (
  CONSTRAINT IMPOSTAZIONI_INTEGR_CG4_CC
  CHECK (INTEGR_CG4 in ('SI','NO'))
  ENABLE VALIDATE);

ALTER TABLE IMPOSTAZIONI_TABLE ADD (
  CONSTRAINT IMPOSTAZIONI_INTEGR_GP4_CC
  CHECK (INTEGR_GP4 in ('SI','NO'))
  ENABLE VALIDATE);

ALTER TABLE IMPOSTAZIONI_TABLE ADD (
  CONSTRAINT IMPOSTAZIONI_INTEGR_GS4_CC
  CHECK (INTEGR_GS4 in ('SI','NO'))
  ENABLE VALIDATE);

ALTER TABLE IMPOSTAZIONI_TABLE ADD (
  CONSTRAINT IMPOSTAZIONI_OBBLIGO_IMBI_CC
  CHECK (OBBLIGO_IMBI is null or (OBBLIGO_IMBI in ('SI','NO')))
  ENABLE VALIDATE);

ALTER TABLE IMPOSTAZIONI_TABLE ADD (
  CONSTRAINT IMPOSTAZIONI_OBBLIGO_SEFI_CC
  CHECK (OBBLIGO_SEFI is null or (OBBLIGO_SEFI in ('SI','NO')))
  ENABLE VALIDATE);

ALTER TABLE IMPOSTAZIONI_TABLE ADD (
  CONSTRAINT IMPOSTAZIONI_VISUALIZZA_CO_CC
  CHECK (VISUALIZZA_CODICE is null or ( VISUALIZZA_CODICE in ('SI','NO') ))
  ENABLE VALIDATE);

ALTER TABLE IMPOSTAZIONI_TABLE ADD (
  CONSTRAINT IMPOSTAZIONI_VISUALIZZA_SU_CC
  CHECK (VISUALIZZA_SUDDIVISIONE is null or ( VISUALIZZA_SUDDIVISIONE in ('SI','NO') ))
  ENABLE VALIDATE);

ALTER TABLE IMPOSTAZIONI_TABLE ADD (
  CONSTRAINT IMPOSTAZIONI_PK
  PRIMARY KEY
  (ID_PARAMETRI)
  USING INDEX IMPOSTAZIONI_PK
  ENABLE VALIDATE);

