ALTER TABLE INDIRIZZI_TELEMATICI ADD (
  CONSTRAINT INDIRIZZI_TEL_TIPO_ENTITA_CC
  CHECK (TIPO_ENTITA in ('AM','AO','UO') and TIPO_ENTITA = upper(TIPO_ENTITA))
  ENABLE VALIDATE);

ALTER TABLE INDIRIZZI_TELEMATICI ADD (
  CONSTRAINT INDIRIZZI_TEL_TIPO_INDIRIZZ_CC
  CHECK (tipo_indirizzo in ('I','R','M','G','F','C','P') and tipo_indirizzo = upper(tipo_indirizzo))
  ENABLE VALIDATE);

ALTER TABLE INDIRIZZI_TELEMATICI ADD (
  CONSTRAINT INDIRIZZI_TELEMATICI_PK
  PRIMARY KEY
  (ID_INDIRIZZO)
  USING INDEX INDIRIZZI_TELEMATICI_PK
  ENABLE VALIDATE);

