ALTER TABLE MODIFICHE_COMPONENTI ADD (
  CONSTRAINT MODIFICHE_COM_OPERAZIONE_CC
  CHECK (OPERAZIONE is null or (OPERAZIONE in ('N','S','C','P','U','A') and OPERAZIONE = upper(OPERAZIONE)))
  ENABLE VALIDATE);

ALTER TABLE MODIFICHE_COMPONENTI ADD (
  CONSTRAINT MODIFICHE_COMPONENTI_PK
  PRIMARY KEY
  (ID_MODIFICA)
  USING INDEX MODIFICHE_COMPONENTI_PK
  ENABLE VALIDATE);

