ALTER TABLE OPERAZIONI_DERIVATE ADD (
  CONSTRAINT OPERAZIONI_DE_ESECUZIONE_CC
  CHECK (ESECUZIONE is null or (ESECUZIONE between -1 and 1))
  ENABLE VALIDATE);

ALTER TABLE OPERAZIONI_DERIVATE ADD (
  CONSTRAINT OPERAZIONI_DERIVATE_PK
  PRIMARY KEY
  (ID_MODIFICA, OTTICA)
  USING INDEX OPERAZIONI_DERIVATE_PK
  ENABLE VALIDATE);

