ALTER TABLE OTTICHE ADD (
  CONSTRAINT OTTICHE_AGGIORNAMENTO_CC
  CHECK (AGGIORNAMENTO_COMPONENTI is null or (AGGIORNAMENTO_COMPONENTI in ('A','M','N') and AGGIORNAMENTO_COMPONENTI = upper(AGGIORNAMENTO_COMPONENTI)))
  ENABLE VALIDATE);

ALTER TABLE OTTICHE ADD (
  CONSTRAINT OTTICHE_GESTIONE_REVI_CC
  CHECK (GESTIONE_REVISIONI in ('SI','NO'))
  ENABLE VALIDATE);

ALTER TABLE OTTICHE ADD (
  CONSTRAINT OTTICHE_OTTICA_ISTITU_CC
  CHECK (OTTICA_ISTITUZIONALE in ('SI','NO'))
  ENABLE VALIDATE);

ALTER TABLE OTTICHE ADD (
  CONSTRAINT OTTICHE_PK
  PRIMARY KEY
  (OTTICA)
  USING INDEX OTTICHE_PK
  ENABLE VALIDATE);

