ALTER TABLE RELAZIONI_RUOLI ADD (
  CONSTRAINT RERU_UO_DISCENDENTI_CC
  CHECK (UO_DISCENDENTI in ('SI','NO'))
  ENABLE VALIDATE);

ALTER TABLE RELAZIONI_RUOLI ADD (
  CONSTRAINT RERU_PK
  PRIMARY KEY
  (ID_RELAZIONE)
  USING INDEX RERU_PK
  ENABLE VALIDATE);

