ALTER TABLE REVISIONI_STRUTTURA ADD (
  CONSTRAINT REVISIONI_STR_STATO_CC
  CHECK (STATO is null or ( STATO in ('A','M','S') ))
  ENABLE VALIDATE);

ALTER TABLE REVISIONI_STRUTTURA ADD (
  CONSTRAINT REVISIONI_STR_TIPO_REVISION_CC
  CHECK (TIPO_REVISIONE is null or (TIPO_REVISIONE in ('N','R') and TIPO_REVISIONE = upper(TIPO_REVISIONE)))
  ENABLE VALIDATE);

ALTER TABLE REVISIONI_STRUTTURA ADD (
  CONSTRAINT REVISIONI_STRUTTURA_PK
  PRIMARY KEY
  (STATO, OTTICA, REVISIONE)
  USING INDEX REVISIONI_STRUTTURA_PK
  ENABLE VALIDATE);

