ALTER TABLE SI4_ABILITAZIONI ADD (
  CONSTRAINT SI4_ABIL_TIAB_FK 
  FOREIGN KEY (ID_TIPO_ABILITAZIONE) 
  REFERENCES SI4_TIPI_ABILITAZIONE (ID_TIPO_ABILITAZIONE)
  ENABLE VALIDATE);

ALTER TABLE SI4_ABILITAZIONI ADD (
  CONSTRAINT SI4_ABIL_TIOG_FK 
  FOREIGN KEY (ID_TIPO_OGGETTO) 
  REFERENCES SI4_TIPI_OGGETTO (ID_TIPO_OGGETTO)
  ENABLE VALIDATE);

