ALTER TABLE SI4_COMPETENZE ADD (
  CONSTRAINT SI4_COMPETENZ_ACCESSO_CC
  CHECK (ACCESSO in ('S','N'))
  ENABLE VALIDATE);

ALTER TABLE SI4_COMPETENZE ADD (
  CONSTRAINT SI4_COMPETENZE_PK
  PRIMARY KEY
  (ID_COMPETENZA)
  USING INDEX SI4_COMPETENZE_PK
  ENABLE VALIDATE);

