ALTER TABLE WORK_REVISIONI ADD (
  CONSTRAINT WORK_REVISION_ERRORE_BLOCCA_CC
  CHECK (ERRORE_BLOCCANTE is null or ( ERRORE_BLOCCANTE in ('SI','NO') ))
  ENABLE VALIDATE);

ALTER TABLE WORK_REVISIONI ADD (
  CONSTRAINT WORK_REVISIONI_PK
  PRIMARY KEY
  (ID_WORK_REVISIONE)
  USING INDEX WORK_REVISIONI_PK
  ENABLE VALIDATE);

